# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

# Mounted under /data
isd_path = "/data/datasets/gridded_isd_oklahoma/2017_corrected.nc"
path_to_pretrained = "/data/datasets/hrrr_oklahoma/hrrr_v3/model_state_dict.pth"
path_to_model_state = "/path/to/my/training-state-000000.pt"
path_to_hrrr = "/data/datasets/hrrr_oklahoma/hrrr_v3/2017.zarr"
path_to_isp = "/data/sda/obs_data/3611864.csv"

# surface obs station data checked into the repo under paper_figures/figure_data/
repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
val_station_path = os.path.join(
    repo_root, "paper_figures/evenmore_random_val_stations.npy"
)  # generated by paper_figures/val_stations.py
station_locations = os.path.join(
    repo_root, "obs/station_locations_on_grid.nc"
)  # generated by obs/preprocess_isd.py
