# Enable flake8-bandit (`S`) and isort (`I`) rules.
select = ["E", "F", "S", "I"]
fixable = ["I"]

# Never enforce `E402`, `E501` (line length violations),
# and `S311` (random number generators)
ignore = ["E402", "E501", "S311"]

extend-exclude = ["modulus/experimental",]

# Ignore `F401` (import violations) in all `__init__.py` files, and in `docs/*.py`.
[per-file-ignores]
"__init__.py" = ["F401"]
"docs/*.py" = ["F401"]

# Ignore `S101` (assertions) in all `test` files.
"test/*.py" = ["S101"]