# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

full_field: &FULL_FIELD

  batch_size: 1
  dt: 1
  n_history: 0
  img_shape_x: 448
  img_shape_y: 448
  # era5_data_dir: '/lustre/fsw/sw_climate_fno/cwb-align'  #old
  # cwb_data_dir: '/lustre/fsw/sw_climate_fno/cwb-rwrf-pad-2212/all_ranges'  #old
  train_data_path: '/lustre/fsw/sw_climate_fno/nbrenowitz/2023-01-24-cwb-4years.zarr'  #'/lustre/fsw/sw_climate_fno/nbrenowitz/2022-01-19-cwb.zarr'   #'/lustre/fsw/sw_climate_fno/nbrenowitz/2023-01-24-cwb-4years.zarr'
  num_data_workers: 1
  normalization: 'zscore'     #minmax
  add_grid: !!bool False      #adds position embedding
  N_grid_channels: 0
  gridtype: 'sinusoidal' #options 'sinusoidal' or 'linear'
  add_topo: !!bool False      #adds position embedding
  ds_factor: 1


# era5-cwb-crop112-grid
full_field_train_crop112_grid_20inchans_4outchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [0,17,18,19]   #[17,18,19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 112
  crop_size_y: 112
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4


full_field_val_crop112_grid_20inchans_4outchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [0,17,18,19]   #[17, 18, 19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 448
  crop_size_y: 448
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4


# era5-cwb-crop112-grid
full_field_train_crop112_grid_20inchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17,18,19]  #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 112
  crop_size_y: 112
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4


full_field_val_crop112_grid_20inchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 448
  crop_size_y: 448
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4


# era5-cwb-crop64-grid
full_field_train_crop64_grid_20inchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 64
  crop_size_y: 64
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4


full_field_val_crop64_grid_20inchans_4x: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 448
  crop_size_y: 448
  N_grid_channels: 4
  add_grid: True
  ds_factor: 4

# era5-cwb-crop64-grid
full_field_train_crop64_grid_20inchans: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 64
  crop_size_y: 64
  N_grid_channels: 4
  add_grid: True


full_field_val_crop64_grid_20inchans: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 448
  crop_size_y: 448
  N_grid_channels: 4
  add_grid: True


# era5-cwb-crop64-grid
full_field_train_crop64_grid: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17, 18, 19]  #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 64
  crop_size_y: 64
  N_grid_channels: 4
  add_grid: True


full_field_val_crop64_grid: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17, 18, 19]      #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 448
  crop_size_y: 448
  N_grid_channels: 4
  add_grid: True



# era5-cwb-crop64
full_field_train_crop64: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17.18,19]        #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 64
  crop_size_y: 64


full_field_val_crop64: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17, 18, 19]      #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 64
  crop_size_x: 448
  crop_size_y: 448


# era5-cwb-crop112
full_field_train_crop112: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17.18,19]        #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 112
  crop_size_y: 112


full_field_val_crop112: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17, 18, 19]      #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 112
  crop_size_x: 112
  crop_size_y: 112


# era5-cwb-crop224
full_field_train_crop224: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17.18,19]        #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 224
  crop_size_x: 224
  crop_size_y: 224


full_field_val_crop224: #config for single gpu training to catch bugs and overfit
  <<: *FULL_FIELD
  in_channels: [17, 18, 19]      #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  out_channels: [17, 18, 19]     #[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  roll: !!bool False
  patch_size: 224
  crop_size_x: 224
  crop_size_y: 224