name: hpo_model_lamb
entity: climate
project: 'highresmip'
program: dummy
method: grid
metric:
  name: valid_loss
  goal: minimize
parameters: 
  optimizer_type: 
    value: 'FusedLAMB'
  weight_decay: 
    value: 1E-6
  batch_size: 
    value: 64
  lr: 
    values: [5E-4, 1E-3]
  patch_size:
    values: [2, 4]
  embed_dim:
    values: [384, 768]
  depth:
    values: [6, 12]
  
