defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .

shape: [2048, 1024]
batch_size: 8
train: true
model:
  num_heads:  32
  qkv_bias:  False
  attn_drop:  0.
  proj_drop:  0.

profile:
  torch: False
  nvtx: False
  line_profiler: False