# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  job:
    chdir: True
  run:
    dir: ./outputs_pino

start_lr: 0.001
gamma: 0.5
max_epochs: 150
milestones: [25, 50, 75, 100, 125, 150]
batchsize: 1

loss:
  derivative: 'modulus' #option to calculate derivatives using 'original' paper or through 'modulus'
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 10.0
  h_loss: 1.0
  u_loss: 1.0
  v_loss: 1.0

data:
  name: 'SWE_Nonlinear'
  total_num: 50
  n_train: 45
  n_test: 5
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
  nin: 1
  nout: 3
  g: 1.0
  H: 1.0
  nu: 0.002


model:
  fno:
    in_channels: 4
    out_channels: 3
    decoder_layers: 1
    decoder_layer_size: 128
    dimension: 3
    latent_channels: 64
    num_fno_layers: 4
    num_fno_modes: 8
    padding: 5

movie:
  val_cbar_index: -1
  err_cbar_index: -1
  remove_frames: True
  font_size: 12
  frame_ext: 'jpg'
  nmovies: 1

