blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://forums.developer.nvidia.com/c/physics-simulation/modulus-physics-ml-model-framework
    about: Thanks for taking the time to ask us a question!