
data_options:
  raw_data_dir: "/mnt/archive/pablo/2024-02-28-rachel"
  metadata_json_path: "../data/2024-3-absnorm"
  mode: "stats" # options: ["train", "test", "stats"]
  builds_train: ["2024-02-26-bridge3-4x27-36_3up-deformation",
                "2024-02-27-incomplete-table-deformation", "2024-02-26-DoubleCantilever3X17-deformation",
                "2024-02-26-I_3mm-deformation", "2024-02-27-TBar-deformation", "2024-02-27-HandAkaFingers-deformation"
                ]
  builds_test: ["2024-02-26-Circle-10mmThickness-with-base-deformation", "2024-02-27-Overhangs_t3_theta0_V3-deformation"]
  f_basename: "volumn-deformation"  # other options before: ["solution", "volumn-deformation"]
  add_anchor: True
  step_size: 5