# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Hyperparameters
hp:
    training_duration: 200000000
    # Training duration based on the number of processed samples
    total_batch_size: 256
    # Total batch size
    batch_size_per_gpu: "auto"
    # Batch size per GPU
    lr: 0.0002
    # Learning rate
    grad_clip_threshold: null
    # no gradient clipping for default non-patch-based training
    lr_decay: 1
    # LR decay rate
    lr_rampup: 0
    # Rampup for learning rate, in number of samples

# Performance
perf:
    fp_optimizations: amp-bf16
    # Floating point mode, one of ["fp32", "fp16", "amp-fp16", "amp-bf16"]
    # "amp-{fp16,bf16}" activates Automatic Mixed Precision (AMP) with {float16,bfloat16}
    dataloader_workers: 4
    # DataLoader worker processes
    songunet_checkpoint_level: 0 # 0 means no checkpointing
    # Gradient checkpointing level, value is number of layers to checkpoint

# IO
io:
    regression_checkpoint_path: ???
    # Where to load the regression checkpoint. Should be overridden.
    print_progress_freq: 1000
    # How often to print progress
    save_checkpoint_freq: 5000
    # How often to save the checkpoints, measured in number of processed samples
    save_n_recent_checkpoints: -1
    # Set to a positive integer to only keep the most recent n checkpoints
    validation_freq: 5000
    # how often to record the validation loss, measured in number of processed samples
    validation_steps: 10
    # how many loss evaluations are used to compute the validation loss per checkpoint
