base: &base_config
  # data config
  num_data_workers: 8 # number of dataloader worker threads per proc
  location: '/pscratch/sd/p/pharring/hrrr_example'
  eos_location: '/lustre/fsw/coreai_climate_earth2/datasets/hrrr/timestepping/'
  dt: 1
  exp_dir: '/pscratch/sd/j/jpathak/hrrr_experiments/'
  eos_exp_dir: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/'
  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  hrrr_img_size: [512, 640]
  n_hrrr_channels: 127
  n_era5_channels: 26
  invariants: []
  linear_grid: !!bool False
  conus_dataset_name: 'hrrr_v3' #versioning for conus dataset, e.g., hrrr, hrrr_v2, hrrr_v3, etc.
  crop_hrrr: !!bool False #required if base dataset (hrrr) does not have nice dims. If set to true the hrrr_img_size will be used to crop the hrrr data
  hrrr_stats: 'stats_v3_2019_2021' #stats files changed to reflect dropped samples from 2017 and half of 2018
  exclude_channels: ['p25', 'p30', 'p35', 'p40', 'z40', 'vil']

  # hyperparameters
  batch_size: 64
  max_epochs: 70
  lr: 1E-3

  enable_nhwc: !!bool False
  optimizer_type: 'FusedAdam'
  clip_grad_norm: None

  two_step_training: !!bool False
  plot_animations: !!bool False

  add_noise: !!bool False
  noise_std: 0

  nettype: 'swin_hrrr'
  embed_dim: 768
  depth: 12
  patch_size: 4
  window_ratio: 32
  num_heads: 8
  drop_path_rate: 0.1
  mlp_ratio: 4

  weight_decay: 0
  residual: !!bool False
  rmse_loss: !!bool False
  relative_loss: !!bool True
  scheduler: 'CosineAnnealingLR'
  target: 'default'
  task: 'forecast'

  add_zenith: !!bool False
  orography: !!bool False
  activation_ckpt: False
  full_pos_embed: True
  rel_pos: False
  mask_ratio: 0
  nonzero_mask: False

  save_checkpoint: !!bool True
  print_every: 100
  validate_every: 100

  boundary_padding_pixels: 0 # set this to 0 for no padding, 32 for 32 pixels of padding in each direction etc.
  localtest: !!bool False

  train_years: [2018, 2019, 2020, 2021]
  valid_years: [2022]

  previous_step_conditioning: !!bool False
  pure_diffusion: !!bool False
  spatial_pos_embed: !!bool False
  P_mean: -1.2 #default edm value
  tendency_normalization: !!bool False
  use_regression_net: !!bool True
  log_scale_residual: !!bool False
  attn_resolutions: []
  ema_freq_kimg: 10

hrrr_v3_1: &v3_1
  <<: *base_config
  batch_size: 64
  n_hrrr_channels: 127
  lr: 5E-4

hrrr_v3_1_log_scale:
  <<: *v3_1
  log_scale: !!bool True
  tendency_stats: "stats_tendency"
  tendency_normalization: !!bool True
  target: "residual_field"
  exclude_channels: ['p25', 'p30', 'p35', 'p40', 'z40', 'q35', 'q40', 'tcwv', 'vil']
  n_hrrr_channels: 124
  lr: 5E-4

diffusion_regression_a2s_v3_1_q: &diffusion_v3_1
  <<: *v3_1
  batch_size: 16 
  num_data_workers: 4
  localtest: !!bool False
  log_to_wandb: !!bool False
  crop_size: 64
  total_kimg: 100000
  img_per_tick: 1000
  input_channels: 'all' #'all' or list of channels to condition on
  diffusion_channels: ['u10m', 'v10m', 't2m', 'refc', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'] #'all' or list of channels to predict
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments/hrrr_v3_1/1/'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/hrrr_v3_1/1/' 
  spatial_pos_embed: !!bool False #None, "add", "concat"
  residual: True
  use_regression_net: True
  loss: "edm"

diffusion_regression_a2s_v3_1_invariants:
  <<: *diffusion_v3_1
  batch_size: 4
  invariants: ["lsm", "orog"]

diffusion_regression_a2s_v3_1_invariants_tendency:
  <<: *diffusion_v3_1
  batch_size: 16
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_normalization: !!bool True
  log_scale: !!bool False
  tendency_stats: "stats_tendency" 
  use_regression_net: !!bool False
  crop_size: 128

diffusion_a2a_v3_1_log_scale:
  <<: *diffusion_v3_1
  batch_size: 32
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_stats: "stats_tendency"
  tendency_normalization:  !!bool True
  log_scale: !!bool True
  exclude_channels: ['p25', 'p30', 'p35', 'p40', 'z40', 'q35', 'q40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  crop_size: 64

regression_a2a_v3_1:
  <<: *diffusion_v3_1
  batch_size: 2
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_stats: "stats_tendency"
  tendency_normalization: !!bool False
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  crop_size: None
  loss: 'regression'

regression_a2a_v3_1_exclude_w:
  <<: *diffusion_v3_1
  batch_size: 64
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_stats: "stats_tendency"
  tendency_normalization: !!bool False
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  crop_size: None
  loss: 'regression'

regression_a2a_v3_1_exclude_w_v2:
  <<: *diffusion_v3_1
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_stats: "stats_tendency"
  tendency_normalization: !!bool False
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  crop_size: None
  loss: 'regression_v2'

regression_a2a_v3_1_exclude_w_v2_noskip:
  <<: *diffusion_v3_1
  batch_size: 64
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_stats: "stats_tendency"
  tendency_normalization: !!bool False
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  crop_size: None
  loss: 'regression_v2'
  validate_every: 5 

diffusion_regression_a2a_v3_1_exclude_w:
  <<: *diffusion_v3_1
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels:  ['u10m', 'v10m', 't2m', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'refc']
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool True
  regression_net_type: 'unet'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/diffusion/' 
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments_eos/'
  crop_size: None
  loss: 'edm'

diffusion_regression_a2a_v3_1_exclude_w_pstep_pos_embed:
  <<: *diffusion_v3_1
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels:  ['u10m', 'v10m', 't2m', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'refc']
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool True
  regression_net_type: 'unet'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/diffusion/' 
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments_eos/'
  previous_step_conditioning: !!bool True
  spatial_pos_embed: !!bool True
  crop_size: None
  loss: 'edm'

diffusion_regression_a2a_v3_1_exclude_w_pstep_pos_embed_v2:
  <<: *diffusion_v3_1
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all"  
  diffusion_channels: "all" 
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool True
  regression_net_type: 'unet2'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/diffusion/' 
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments_eos/'
  previous_step_conditioning: !!bool True
  spatial_pos_embed: !!bool True
  crop_size: None
  loss: 'edm'

diffusion_regression_a2a_v3_1_exclude_w_pos_embed:
  <<: *diffusion_v3_1
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels:  ['u10m', 'v10m', 't2m', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'refc']
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool True
  regression_net_type: 'unet'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/diffusion/' 
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments_eos/'
  crop_size: None
  spatial_pos_embed: !!bool True
  loss: 'edm'

diffusion_regression_a2a_v3_1_exclude_w_pstep_pos_embed_direct:
  <<: *diffusion_v3_1
  residual: !!bool False
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels:  ['u10m', 'v10m', 't2m', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'refc']
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool True
  regression_net_type: 'unet'
  eos_regression_model_basepath: '/lustre/fsw/coreai_climate_earth2/jpathak/hrrr-experiments/diffusion/' 
  regression_model_basepath: '/pscratch/sd/j/jpathak/hrrr_experiments_eos/'
  previous_step_conditioning: !!bool True
  spatial_pos_embed: !!bool True
  crop_size: None
  loss: 'edm'

pure_diffusion_a2a_v3_1_exclude_w_pstep_pos_embed_direct:
  <<: *diffusion_v3_1
  residual: !!bool False
  batch_size: 1
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels:  "all"
  log_scale: !!bool False
  exclude_channels: ['u35', 'u40', 'v35', 'v40', 't35', 't40', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40', 'p25', 'p30', 'p35', 'p40', 'z35', 'z40', 'tcwv', 'vil']
  use_regression_net: !!bool False
  spatial_pos_embed: !!bool True
  pure_diffusion: !!bool True
  crop_size: None
  loss: 'edm'


diffusion_v3_1_invariants_tendency_grid_full_field:
  <<: *diffusion_v3_1
  batch_size: 128
  invariants: ["lsm", "orog"]
  input_channels: "all" 
  diffusion_channels: "all" 
  tendency_normalization: !!bool True
  tendency_stats: "stats_tendency" 
  use_regression_net: !!bool False
  linear_grid: !!bool True
  crop_size: None

diffusion_regression_a2s_v3_1_u_v_q_t_w_nopos_crop128:
  <<: *diffusion_v3_1
  spatial_pos_embed: !!bool False
  crop_size: 128
  diffusion_channels: ['u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10','t1', 't2','t3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10'] #'all' or list of channels to predict
  invariants: ["lsm", "orog"]

diffusion_regression_a2a_v3_1_tune:
  <<: *diffusion_v3_1
  batch_size: 64
  spatial_pos_embed: !!bool False
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'u35', 'u40', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 'v35', 'v40', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 't35', 't40', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40']
  crop_size: 128
  invariants: ["lsm", "orog"]
  linear_grid: !!bool True
  use_regression_net: !!bool True

diffusion_regression_a2a_v3_1_log_residual:
  <<: *diffusion_v3_1
  batch_size: 2
  spatial_pos_embed: !!bool False
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'u35', 'u40', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 'v35', 'v40', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 't35', 't40', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40']
  crop_size: 128 
  invariants: ["lsm", "orog"]
  linear_grid: !!bool True
  use_regression_net: !!bool True
  log_scale_residual: !!bool True
  clip_grad_norm: 100000

diffusion_regression_a2a_v3_1_log_residual_nocrop:
  <<: *diffusion_v3_1
  batch_size: 64
  spatial_pos_embed: !!bool False
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30']   
  crop_size: None
  invariants: ["lsm", "orog"]
  linear_grid: !!bool True
  use_regression_net: !!bool True
  log_scale_residual: !!bool True

diffusion_regression_a2a_v3_1_log_residual_nocrop_attn:
  <<: *diffusion_v3_1
  batch_size: 64
  spatial_pos_embed: !!bool False
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30']   
  crop_size: None
  invariants: ["lsm", "orog"]
  linear_grid: !!bool True
  use_regression_net: !!bool True
  log_scale_residual: !!bool True
  attn_resolutions: [32]

diffusion_regression_a2a_v3_1_log_residual_nocrop_attn_pstep_pstd_2_0:
  <<: *diffusion_v3_1
  batch_size: 64
  spatial_pos_embed: !!bool False
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30']   
  crop_size: None
  invariants: ["lsm", "orog"]
  linear_grid: !!bool True
  use_regression_net: !!bool True
  log_scale_residual: !!bool True
  attn_resolutions: [32]
  previous_step_conditioning: !!bool True
  P_std: 2.0

diffusion_regression_a2s_v3_1_u_v_q_t_w_nopos_crop128_all_levels:
  <<: *diffusion_v3_1
  spatial_pos_embed: !!bool False
  crop_size: 128
  diffusion_channels: [ 'u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'u11', 'u13', 'u15', 'u20', 'u25', 'u30', 'u35', 'u40', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v13', 'v15', 'v20', 'v25', 'v30', 'v35', 'v40', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't13', 't15', 't20', 't25', 't30', 't35', 't40', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q13', 'q15', 'q20', 'q25', 'q30', 'q35', 'q40', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w13', 'w15', 'w20', 'w25', 'w30', 'w35', 'w40'] 
  invariants: ["lsm", "orog"]


diffusion_regression_a2s_v3_1_u_v_q_t_w_nopos_crop128_pstep:
  <<: *diffusion_v3_1
  spatial_pos_embed: !!bool False
  crop_size: 128
  diffusion_channels: ['u10m', 'v10m', 't2m', 'refc', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10','t1', 't2','t3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10'] #'all' or list of channels to predict
  invariants: ["lsm", "orog"]
  previous_step_conditioning: True

diffusion_regression_a2s_v3_1_pstep_conditioning:
  <<: *diffusion_v3_1
  batch_size: 4
  previous_step_conditioning: True


diffusion_regression_a2s_v3_1:
  <<: *diffusion_v3_1
  diffusion_channels: ['u10m', 'v10m', 't2m', 'refc'] #'all' or list of channels to predict

diffusion_regression_a2a_v3_1:
  <<: *diffusion_v3_1
  diffusion_channels: 'all' #'all' or list of channels to predict

diffusion_regression_a2a_v3_1_direct:
  <<: *diffusion_v3_1
  diffusion_channels: 'all'
  use_regression_net: False
  residual: True


