# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

model:
  space_dim: 2
  n_layers: 8
  n_hidden: 128
  dropout: 0.0
  n_head: 8
  Time_Input: False
  act: gelu
  mlp_ratio: 1
  fun_dim: 1
  out_dim: 1
  slice_dim: 32
  ref: 8
  unified_pos: 1
  slice_num: 64
  


normaliser:
  permeability:
    mean: 1.25
    std_dev: .75
  darcy:
    mean: 4.52E-2
    std_dev: 2.79E-2

scheduler:
  initial_lr: 1.E-3
  decay_rate: 1.E-5
  weight_decay: 1.E-5
  decay_pseudo_epochs: 8

training:
  resolution: 85
  batch_size: 4
  rec_results_freq : 100
  max_pseudo_epochs: 500
  pseudo_epoch_sample_size: 1000

validation:
  sample_size: 200
  validation_pseudo_epochs: 2
