cd /lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/feathered-curassow_2023.04.13_09.43/code; PYTHONPATH=/lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/feathered-curassow_2023.04.13_09.43/code exec torchrun  --nnodes=1  --nproc_per_node=1  --max_restarts=3  --rdzv_id=1   --rdzv_backend=c10d   --rdzv_endpoint=localhost:29400   train.py --batch 256 --batch-gpu 2 --augment 0.0 --arch ddpmpp-cwb-v0 --precond mixturev2 --data /lustre/fsw/sw_climate_fno/nbrenowitz/2023-01-24-cwb-4years.zarr --outdir /lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/feathered-curassow_2023.04.13_09.43/output --lr 2e-4 --duration 200 --snap 1 --dump 1 --workers 4 --data_config full_field_train_crop448_grid_12inchans_fcn_4outchans_4x_normv2 --task sr --data_type era5-cwb-v3



#batch
# SUBMIT_SUBPROJECT_NAME=earth2-diffusion  submit_job --image gitlab-master.nvidia.com/tkurth/era5_wind:latest --duration 4 --autoresume_timer 235 --nodes 8 --gpu 8 --mounts $SHARE_SOURCE,$SHARE_OUTPUT,$SHARE_DATA,/lustre/fsw --setenv SUBMIT_ACCOUNT=sw_earth2_ml --partition luna  --name edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization_wandering-mandrill_2023.04.13_10.17 --command ' cd /lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/wandering-mandrill_2023.04.13_10.17/code; PYTHONPATH=/lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/wandering-mandrill_2023.04.13_10.17/code exec torchrun  --nproc_per_node=${SUBMIT_GPUS} --nnodes=8 --node_rank=${NODE_RANK}  --master_addr=${MASTER_ADDR} --master_port=${MASTER_PORT}  train.py --batch 256 --batch-gpu 1 --augment 0.0 --arch ddpmpp-cwb-v0 --precond mixturev2 --data /lustre/fsw/sw_climate_fno/nbrenowitz/2023-01-24-cwb-4years.zarr --outdir /lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/wandering-mandrill_2023.04.13_10.17/output --lr 2e-4 --duration 200 --snap 1 --dump 1 --workers 4 --data_config full_field_train_crop448_grid_12inchans_fcn_4outchans_4x_normv2 --task sr --data_type era5-cwb-v3  ' --logdir /lustre/fsw/nvresearch/mmardani/output/logs/edm_era5_cwb_12chans_fcn_4x_crop448_zarr_fulldata_mixturev2_normalization/wandering-mandrill_2023.04.13_10.17/gcf_log





