# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Model name
model_name: 'regression' # 'regression', 'diffusion', or custom model added by user

# Model hyperparameters
previous_step_conditioning: False # Whether or not to condition on the previous step outputs as well (enable for diffusion)
spatial_pos_embed: False # Whether or not to add an additive position embed after the first conv in the U-Net
P_mean: -1.2 # Center of the EDM lognormal noise sampling distribution
attn_resolutions: [] # Internal resolutions within the U-Net to apply self-attention (empty list == no self-attention)

# Pretrained regression model
use_regression_net: False # Whether or not to use a regression net as a first step (enable for diffusion training)
regression_weights: "stormcast_checkpoints/regression/UNet.0.0.mdlus" # Path to pretrained regression network,
                                                                      # used if use_regression_net=True
